### ISSUE TITLE
 cannot import name 'Transactions'

### ISSUE THREAD

**Issue by vince06fr** [ascribe/transactions#66]
>>> from transactions import Transactions
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/env/lib/python3.5/site-packages/transactions/__init__.py", line 1, in <module>
    from transactions import Transactions   # noqa
ImportError: cannot import name 'Transactions'

**Comment by sbellem** [comment]
Python 3 is not supported at the moment. Hopefully by the end of this week it will be. Issue #67 is up next on my todo list.

**Comment by sbellem** [comment]
Hi @vince06fr, version `0.2.0` was just uploaded to PyPI, and has support for Python 3. 

```bash
pip install --upgrade transactions==0.2.0
```

Please let me know if you have any questions. I will close this issue now as PRs #68 and #69 are expected to have resolved the issue.
