### ISSUE TITLE
Possible errors in the Theory / Coin Transfer and Double-spending sections

### ISSUE THREAD

**Issue by cjauvin** [ascribe/transactions#71]
I'm not 100% certain, but it would seem that Alice's transfers should be signed with _her_ private key (i.e. `alice_private_key`), instead of Goofy's, in these two examples:

https://github.com/ascribe/transactions/blame/master/docs/source/theory.rst#L287

https://github.com/ascribe/transactions/blame/master/docs/source/theory.rst#L303

**Comment by sbellem** [comment]
Thanks! Fixed in #72
